---
- name: Include OS-specific variables
  include_vars: "{{ ansible_facts['distribution'] }}.yml"

- name: Add additional repositories
  block:
    - name: Import RPM Fusion GPG keys
      rpm_key:
        key: "{{ item }}"
        state: present
      with_items:
        # yamllint disable-line rule:line-length
        - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ hostvars[inventory_hostname].ansible_distribution_major_version }}" # noqa 204
        # yamllint disable-line rule:line-length
        - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-{{ hostvars[inventory_hostname].ansible_distribution_major_version }}" # noqa 204

    - name: Install RPM Fusion repository packages
      package:
        name: "{{ additional_repos }}"
        state: present

- name: Install Vulkan development packages
  package:
    name: "{{ development_packages }}"
    state: present
  when: install_devel
  notify:
    - reboot

- name: Install Vulkan packages for NVIDIA
  package:
    name: "{{ nvidia_packages }}"
    state: present
  when: gpu_vendor == "nvidia" or gpu_vendor == "all"
  notify:
    - reboot

- name: Install Vulkan packages for AMD
  package:
    name: "{{ amd_packages }}"
    state: present
  when: gpu_vendor == "amd" or gpu_vendor == "all"
  notify:
    - reboot

- name: Install Vulkan packages for Intel
  package:
    name: "{{ intel_packages }}"
    state: present
  when: gpu_vendor == "intel" or gpu_vendor == "all"
  notify:
    - reboot
